# Generated by Django 5.2.13 on 2026-04-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bricks',
            field=models.FloatField(default=0, max_length=309),
        ),
        migrations.AddField(
            model_name='member',
            name='charge',
            field=models.FloatField(default=0, max_length=309),
        ),
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.FloatField(default=0, max_length=309),
        ),
        migrations.AddField(
            model_name='member',
            name='tokens',
            field=models.FloatField(default=0, max_length=309),
        ),
    ]
