# Generated by Django 5.2.13 on 2026-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0003_profile_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_per_click',
            field=models.IntegerField(default=1),
        ),
    ]
