# Generated by Django 5.2.13 on 2026-06-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0004_profile_points_per_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_cost', models.IntegerField()),
                ('click_multiplier', models.FloatField(default=1.0)),
                ('effect_type', models.CharField(choices=[('click_power', 'Click Power'), ('auto_click', 'Auto Click'), ('additive_multiplier', 'Additive Multiplier'), ('global_multiplier', 'Global Multiplier')], max_length=30)),
                ('effect_value', models.FloatField()),
                ('is_repeatable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.profile')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.upgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
    ]
