# Generated by Django 5.2.13 on 2026-06-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0005_upgrade_profileupgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileupgrade',
            old_name='player',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='profileupgrade',
            unique_together={('profile', 'upgrade')},
        ),
    ]
