# Generated by Django 5.2.13 on 2026-06-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0006_rename_player_profileupgrade_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='click_multiplier',
        ),
    ]
