# Generated by Django 5.2.13 on 2026-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0007_remove_upgrade_click_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='cost_multiplier',
            field=models.FloatField(default=1.15),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='effect_type',
            field=models.CharField(choices=[('click_power', 'Click Power'), ('auto_click', 'Auto Click'), ('additive_power', 'Additive Power'), ('additive_multiplier', 'Additive Multiplier'), ('global_multiplier', 'Global Multiplier')], max_length=30),
        ),
    ]
