# Generated by Django 5.2.13 on 2026-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0008_upgrade_cost_multiplier_alter_upgrade_effect_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='cost_increase',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='cost_type',
            field=models.CharField(choices=[('exp', 'Exponential'), ('linear', 'Linear'), ('fixed', 'Fixed')], default='exp', max_length=20),
        ),
    ]
