# Generated by Django 5.2.13 on 2026-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0009_upgrade_cost_increase_upgrade_cost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crystals',
            field=models.IntegerField(default=0),
        ),
    ]
