# Generated by Django 5.2.13 on 2026-06-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0010_profile_crystals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('effect_type', models.CharField(max_length=50)),
                ('effect_value', models.FloatField()),
                ('repeatable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPrestigeUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.profile')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.prestigeupgrade')),
            ],
        ),
    ]
