# Generated by Django 5.2.13 on 2026-06-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0011_prestigeupgrade_playerprestigeupgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestigeupgrade',
            old_name='repeatable',
            new_name='is_repeatable',
        ),
    ]
