# Generated by Django 5.2.13 on 2026-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0012_rename_repeatable_prestigeupgrade_is_repeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='currency',
            field=models.CharField(choices=[('normal', 'Normal'), ('prestige', 'Prestige')], default='normal', max_length=20),
        ),
    ]
