# Generated by Django 5.2.13 on 2026-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0013_upgrade_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='effect_type',
            field=models.CharField(choices=[('click_power', 'Click Power'), ('auto_click', 'Auto Click'), ('additive_power', 'Additive Power'), ('additive_multiplier', 'Additive Multiplier'), ('global_multiplier', 'Global Multiplier'), ('crystal_additive', 'Crystal Additive'), ('crystal_multiplier', 'Crystal Multiplier')], max_length=30),
        ),
        migrations.DeleteModel(
            name='PlayerPrestigeUpgrade',
        ),
        migrations.DeleteModel(
            name='PrestigeUpgrade',
        ),
    ]
