# Generated by Django 5.2.13 on 2026-06-21 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0014_alter_upgrade_effect_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_collected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
