# Generated by Django 5.2.13 on 2026-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0015_profile_last_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prestige_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
