# Generated by Django 5.2.13 on 2026-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0016_profile_prestige_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='asteroid_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='asteroids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='currency',
            field=models.CharField(choices=[('normal', 'Normal'), ('prestige', 'Prestige'), ('asteroid', 'Asteroid')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='effect_type',
            field=models.CharField(choices=[('click_power', 'Click Power'), ('auto_click', 'Auto Click'), ('additive_power', 'Additive Power'), ('additive_multiplier', 'Additive Multiplier'), ('global_multiplier', 'Global Multiplier'), ('crystal_additive', 'Crystal Additive'), ('crystal_multiplier', 'Crystal Multiplier'), ('asteroid_gain', 'Asteroid Gain'), ('crystal_keep', 'Keep Crystals'), ('prestige_keep', 'Keep Prestige'), ('autoclick_multiplier', 'Autoclick Multiplier')], max_length=30),
        ),
    ]
